version: '3.8'

services:
  code-generation-app:
    build: .
    container_name: code-generation
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
      # JWT Configuration
      - APP_JWT_SECRET=${JWT_SECRET}
      - APP_JWT_EXPIRATION=86400000
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
